# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47b614b4e96ec608bf855a3817d2fd708afd34964fe89d8f43e5aa32c44ca25c0c18c120048ffa3a2cfd8807382eba4f143a582593ede9be60138b02b78d8d94

test:
  secret_key_base: 7a3b6cc4a6f4fde60e63f97b18991fb570493594098acbd8b1909204a7af9ba02e3daa80e3f5d71b3fbee8b2b634bd499a9a37fb26ca25cb72ce5d175ed2c5bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
